name: PostgreSQL Restore (Local)

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  restore-db:
    runs-on: self-hosted

    steps:
      - name: Checkout Code (Optional)
        uses: actions/checkout@v3

   #   - name: Install PostgreSQL Tools (if needed)
     #   run: |
   #       choco install postgresql --no-progress
    #    shell: powershell

      - name: Restore PostgreSQL Backup
        run: |
          & "C:\Program Files\PostgreSQL\17\bin\pg_restore.exe" -U sonar -h localhost -d sonarqubebackup -v "C:\temp\mydb.backup"
        shell: powershell
        env:
          PGPASSWORD: ${{ secrets.PG_PASSWORD }}
