name: Local Postgres Backup and Restore

on:
#  schedule:
#    - cron: '0 3 * * *'  # Every day at 3 AM UTC
  workflow_dispatch:

jobs:
  backup-restore:
    runs-on: self-hosted

    env:
      SRC_PG_HOST: localhost
      SRC_PG_PORT: 5432
      SRC_PG_USER: postgres
      SRC_PG_PASSWORD: postgres
      SRC_PG_DATABASE: postgres

      TARGET_PG_HOST: localhost
      TARGET_PG_PORT: 5433
      TARGET_PG_USER: sonar
      TARGET_PG_PASSWORD: sonar
      TARGET_PG_DATABASE: sonarqubebackup

    steps:
 #     - name: Install PostgreSQL client (if needed)
 #       run: |
 #         sudo apt-get update
  #        sudo apt-get install -y postgresql-client


      - name: Run PowerShell Backup Script
        run: powershell.exe -ExecutionPolicy Bypass -File .\backup-restore.ps1
