
name: PostgreSQL Backup (Local)

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  backup-db:
    runs-on: self-hosted

    steps:
      - name: Checkout Code (Optional)
        uses: actions/checkout@v3
      - name: Backup SonarQube Database in  PostgreSQL Backup
        run: |
          $timestamp = Get-Date -Format "yyyyMMddHHmmss"
          $backupFile = "C:\temp\pg_backup_$timestamp.dump"
          & "C:\Program Files\PostgreSQL\17\bin\pg_dump.exe"  -U postgres -h localhost -F c -b -v -f  $backupFile  postgres
        shell: powershell
        env:
          PGPASSWORD: ${{ secrets.PG_PASSWORD }}
